---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: maven
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']


- name: Install Maven download directory (remote)
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ ansible_data_path }}


- name: Download Maven (remote)
  tags: maven
  get_url: 
    dest={{ ansible_data_path }}/{{ maven_redis_filename }}
    url={{ maven_mirror }}/maven-{{ maven_version_major }}/{{ maven_version }}/binaries/{{ maven_redis_filename }}
    owner=0
    group=0
    mode=0644
    sha256sum={{ maven_redis_sha256sum }}


- name: Install Maven installation directory
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_install_dir }}


- name: Install Maven
  tags: maven
  unarchive:
    src={{ ansible_data_path }}/{{ maven_redis_filename }}
    dest={{ maven_install_dir }}
    copy=no


- name: Install Maven bin directory
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_bin_path }}


- name: Install Maven binary
  tags: maven
  file:
    state=link
    force=true
    src={{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn
    dest={{ maven_bin_path }}/mvn
