---
# Version of our role.
maven_role_version: '0.1.1'

# path for ansible to store downloaded or templated data
ansible_data_path: '/usr/local/src/ansible/data'

# base installation directory for any Maven distribution
maven_install_dir: '/opt/maven'

# concatenated Maven version
maven_version: "{{ maven_version_major }}.{{ maven_version_minor }}.{{ maven_version_patch }}"

# filename of Maven redistributable package
maven_redis_filename: "apache-maven-{{ maven_version }}-bin.tar.gz"
