---

- name: plugins | Download nexus plugins
  get_url:
    url={{item.url}}/{{item.file}}
    dest="{{nexus_dir_tmp}}"
  with_items: nexus_plugins
  register: download_results 
  ignore_errors: yes
  tags: nexus

- name: plugins | Messange on dep fail
  fail: msg="For some reason nexus repo broke. Please check link"
  when: download_results | failed

- name: plugins | Unarchive nexus plugins
  unarchive: 
    copy=no
    src="{{nexus_dir_tmp}}/{{item.file}}"
    dest="{{nexus_dir_plugins}}/"
  sudo_user: "{{nexus_user}}"
  when: download_results | changed
  with_items: nexus_plugins  
  tags: nexus